### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by mashumashu** [nok/markdown-toc#29] opened 2015-06-23 12:54 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `markdown-toc` package
```
Package.getStylesheetsPath (C:\Users\takama\AppData\Local\atom\app-0.210.0\resources\app.asar\src\package.js:460:9)
Package.getStylesheetPaths (C:\Users\takama\AppData\Local\atom\app-0.210.0\resources\app.asar\src\package.js:471:32)
Package.loadStylesheets (C:\Users\takama\AppData\Local\atom\app-0.210.0\resources\app.asar\src\package.js:453:38)
<unknown> (C:\Users\takama\AppData\Local\atom\app-0.210.0\resources\app.asar\src\package.js:185:19)
Package.measure (C:\Users\takama\AppData\Local\atom\app-0.210.0\resources\app.asar\src\package.js:165:15)
Package.load (C:\Users\takama\AppData\Local\atom\app-0.210.0\resources\app.asar\src\package.js:179:12)
```

**Comment by mainiak** [comment] 2015-06-24 22:26
Duplicate for #20

**Comment by nok** [comment] 2015-07-07 06:44
Duplicate of https://github.com/nok/markdown-toc/issues/35.

**Comment by nok** [comment] 2015-07-07 06:47
By the way, thanks @mainiak for supporting these issues. :-)

**Closed by nok** 2015-07-07 06:47 UTC
Labels: duplicate
