### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by SalathielGenese** [nok/markdown-toc#30] opened 2015-06-25 10:24 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `markdown-toc` package
```
Package.getStylesheetsPath (/opt/atom/resources/app.asar/src/package.js:460:9)
Package.getStylesheetPaths (/opt/atom/resources/app.asar/src/package.js:471:32)
Package.loadStylesheets (/opt/atom/resources/app.asar/src/package.js:453:38)
<unknown> (/opt/atom/resources/app.asar/src/package.js:185:19)
Package.measure (/opt/atom/resources/app.asar/src/package.js:165:15)
Package.load (/opt/atom/resources/app.asar/src/package.js:179:12)
```

**Comment by nok** [comment] 2015-07-07 06:44
Duplicate of https://github.com/nok/markdown-toc/issues/35.

**Closed by nok** 2015-07-07 06:44 UTC

**Comment by SalathielGenese** [comment] 2015-07-09 11:42
Sorry, atom generates this automatically

**Comment by nok** [comment] 2015-07-09 11:45
Well, it's a neat service by GitHub. :-)

**Comment by SalathielGenese** [comment] 2015-07-10 11:02
ok
